#!/usr/bin/env bash

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 103}' -o 103.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 104}' -o 104.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 200}' -o 200.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 201}' -o 201.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 202}' -o 202.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 203}' -o 203.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 207}' -o 207.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 208}' -o 208.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 209}' -o 209.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 210}' -o 210.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 704}' -o 704.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 302}' -o 302.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 303}' -o 303.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 306}' -o 306.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 307}' -o 307.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 310}' -o 310.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 311}' -o 311.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 401}' -o 401.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 402}' -o 402.csv
mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 403}' -o 403.csv

mongoexport --type=csv -f company_name,item_category_num,item_category,phone,license_number,unified_social_credit_code,organization_registration_code,registration_number,business_status,business_type,register_date,legal_representative,operating_period,registered_capital,date_of_issue,registration_authority,business_address,business_scope,url -d bjda -c company_info_items_clean -q '{"item_category_num": 502}' -o 502.csv